id: IE73E3138
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:07:38+00:00'
last_modified: '2022-06-08T06:17:32.844836+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18254
  title: གསང་ཆེན་རྡོ་རྗེ་ཐེག་པའི་ས་ལམ་གྱི་རྣམ་བཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    17C1:
      image_group_id: I1KG18300
      title: ''
      total_pages: 266
      order: 1
      base_file: 17C1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
